#************************************************************
# This file was automatically generated by Smart Configurator
#************************************************************

# Get user configuration settings
# It can also be used to specify the target environment location
# e.g compiler's location. This variable is most useful when crosscompiling.
# Note, CMake doesn't support CC-RH compiler.
# Even if it finds the executable, it does not know its identification.
include("${CMAKE_CURRENT_LIST_DIR}/Config.cmake")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR RH)

# do some windows specific logic
if(WIN32)
    set(TOOLCHAIN_EXT ".exe")
else()
    set(TOOLCHAIN_EXT "")
endif(WIN32)

# Find Renesas CC-RH.
find_compiler(RENESAS_COMPILER_CC ccrh)
find_compiler(RENESAS_COMPILER_ASM ccrh)

# Specify the LIB path of the toolchain
set(CMAKE_CCRH_LIB_PATH "${RENESAS_TOOLCHAIN_PATH}/../lib")

# Specify the cross compiler.
set(CMAKE_C_COMPILER_ID CCRH)
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER ${RENESAS_TOOLCHAIN_PATH}/ccrh${TOOLCHAIN_EXT} CACHE FILEPATH "C compiler")
set(CMAKE_ASM_COMPILER ${RENESAS_TOOLCHAIN_PATH}/ccrh${TOOLCHAIN_EXT} CACHE FILEPATH "ASM compiler")

# Don't look for executable in target system prefix.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Look for includes and libraries only in the target system prefix.
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Disable compiler checks.
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_ASM_COMPILER_FORCED TRUE)

# Specify the linker
set(CMAKE_LINKER ${RENESAS_TOOLCHAIN_PATH}/rlink${TOOLCHAIN_EXT})

# Specify the Converter
set(CMAKE_CONVERTER_EXECUTABLE "${RENESAS_TOOLCHAIN_PATH}/rlink${TOOLCHAIN_EXT}" CACHE FILEPATH "CCRH ABS Converter")

#****************************
# END OF CMAKE TOOLCHAIN FILE
#****************************