
#************************************************************
# This file was automatically generated by Smart Configurator
#************************************************************

# Source directories
#FILE (GLOB_RECURSE SOURCE ${CMAKE_SOURCE_DIR}
#    "*.c" "*.asm" "*.h"
#)

#FILE (GLOB_RECURSE Source_ASM ${CMAKE_SOURCE_DIR} "*.asm")
SET (ASM_FILES 
<%- asm_files%>)

foreach(X IN LISTS ${ASM_FILES})
    set_source_files_properties(${X} PROPERTIES LANGUAGE ASM)
endforeach()

add_executable(${PROJECT_NAME} 
<%- all_files%>)

# Include all directories to ${PROJECT_NAME} to search header files
# target_sources(${PROJECT_NAME} PRIVATE ${RENESAS_TOOLCHAIN_PATH}/../inc)

target_include_directories(${PROJECT_NAME}
    PRIVATE
	${RENESAS_TOOLCHAIN_PATH}/../inc
<%- include_path%>
)

#*******************************************************
# Custom commands to generate *.abs and *.x files
#*******************************************************

# Set output file type:
set(Convert_Command <%= output_options %>)
# Set Converter Command
add_custom_command (
 POST_BUILD
 TARGET ${PROJECT_NAME}
 COMMAND ${CMAKE_CONVERTER_EXECUTABLE} ${PROJECT_NAME}.abs ${Convert_Command}
 COMMENT "Converter:"
 VERBATIM
)

# Set the CC Converter
set(CMAKE_COMMAND "${CMAKE_TOOLS_FOLDER}/ccrh/renesas_cc_converter${TOOLCHAIN_EXT}")
# Add command for building with CC Converter
add_custom_command(
 POST_BUILD
 TARGET ${PROJECT_NAME}
 COMMAND ${CMAKE_COMMAND} "${PROJECT_NAME}.abs" "${PROJECT_NAME}.x"
 VERBATIM
)

#*****************************
# END OF GENERATED SOURCE FILE
#*****************************
