
#************************************************************
# This file was automatically generated by Smart Configurator
#************************************************************

# Set C/ASM flags
set(C_COMPILER_OPTIONS "${C_COMPILER_OPTIONS} <%- c_compiler_options %>")
set(ASM_COMPILER_OPTIONS "${ASM_COMPILER_OPTIONS} <%- asm_compiler_options %>")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${C_COMPILER_OPTIONS} <INCLUDES>")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ASM_COMPILER_OPTIONS}")

# Specify C/ASM compiler option
set(CMAKE_C_COMPILE_OBJECT "${CMAKE_C_COMPILER} ${CMAKE_C_FLAGS} -o<OBJECT> <SOURCE>")
set(CMAKE_ASM_COMPILE_OBJECT "${CMAKE_ASM_COMPILER} ${CMAKE_ASM_FLAGS} -o<OBJECT> <SOURCE>")

# Specify Library option
set(FLOAT_MODE "<%- float_mode %>")
set(CMAKE_EXE_LIB_INCLUDES "")

# Set linker flags
set(CMAKE_EXE_LINKER_FLAGS "<%- link_options %>")

# Specify executable option
set(CMAKE_C_LINK_EXECUTABLE "\"${CMAKE_LINKER}\" ${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LIB_INCLUDES} <OBJECTS>")

# Specify archiver option
SET(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS 0)

#*****************************
# END OF GENERATED CONFIG FILE
#*****************************
